/*
 * generated by Xtext 2.25.0
 */
package de.fraunhofer.ipa.ros2.ide.contentassist.antlr;

import de.fraunhofer.ipa.ros2.ide.contentassist.antlr.internal.InternalRos2Parser;
import org.antlr.runtime.Token;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.parser.antlr.AbstractIndentationTokenSource;

public class Ros2TokenSource extends AbstractIndentationTokenSource {

    private static final int RULE_WS;
    private static final int RULE_BEGIN;
    private static final int RULE_END;

    static {
        int ws = 0, begin = 0, end = 0;
        try {
            ws = InternalRos2Parser.class.getField("RULE_WS").getInt(null);
            begin = InternalRos2Parser.class.getField("RULE_BEGIN").getInt(null);
            end = InternalRos2Parser.class.getField("RULE_END").getInt(null);
        } catch (Exception e) {
            ws = InternalRos2Parser.RULE_WS;
            begin = InternalRos2Parser.RULE_BEGIN;
            end = InternalRos2Parser.RULE_END;
        }
        RULE_WS = ws;
        RULE_BEGIN = begin;
        RULE_END = end;
    }

    public Ros2TokenSource(TokenSource delegate) {
        super(delegate);
    }

    @Override
    protected boolean shouldSplitTokenImpl(Token token) {
        return token.getType() == RULE_WS;
    }

    @Override
    protected int getBeginTokenType() {
        return RULE_BEGIN;
    }

    @Override
    protected int getEndTokenType() {
        return RULE_END;
    }

    @Override
    protected boolean shouldEmitPendingEndTokens() {
        return false;
    }
}
