package de.fraunhofer.ipa.ros2.generator

import com.google.inject.Inject
import ros.Node
import ros.Package

class Ros2PythonWrapperCompiler {

    @Inject extension Ros2GeneratorHelpers

    def String compileWrapper(Package pkg, Node node) '''
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Generated ROS 2 Node Wrapper for '«node.name»'.
DO NOT EDIT THIS FILE DIRECTLY - it will be overwritten on generation.
Implement your domain logic in the corresponding logic class or inherit from this wrapper.
"""

import threading
from typing import Optional, Callable, Any, List

import rclpy
from rclpy.node import Node
from rclpy.callback_groups import ReentrantCallbackGroup
from rclpy.qos import QoSProfile, ReliabilityPolicy, DurabilityPolicy
from rcl_interfaces.msg import ParameterDescriptor, SetParametersResult

«IF node.hasActions»
from rclpy.action import ActionServer, ActionClient, GoalResponse, CancelResponse
«ENDIF»

# ROS 2 Interfaces imports
«FOR pub : node.publisher»
from «pub.message.specPackage».msg import «pub.message.specName»
«ENDFOR»
«FOR sub : node.subscriber»
from «sub.message.specPackage».msg import «sub.message.specName»
«ENDFOR»
«FOR srv : node.serviceserver»
from «srv.service.specPackage».srv import «srv.service.specName»
«ENDFOR»
«FOR client : node.serviceclient»
from «client.service.specPackage».srv import «client.service.specName»
«ENDFOR»
«FOR act : node.actionserver»
from «act.action.specPackage».action import «act.action.specName»
«ENDFOR»
«FOR actClient : node.actionclient»
from «actClient.action.specPackage».action import «actClient.action.specName»
«ENDFOR»


class «node.name»Wrapper(Node):
    """
    ROS 2 Wrapper for «node.name» encapsulating all middleware communication.
    """

    def __init__(self, node_name: str = "«node.name»", **kwargs):
        super().__init__(node_name, **kwargs)
        self._cb_group = ReentrantCallbackGroup()

        # ----------------------------------------------------
        # 1. Parameter Declarations (with and without defaults)
        # ----------------------------------------------------
        «FOR param : node.parameter»
        «val defaultVal = getParamDefaultValuePython(param)»
        desc_«sanitizeName(param.name)» = ParameterDescriptor(
            description="Parameter '«param.name»' modelled in RosTooling",
            read_only=False
        )
        «IF defaultVal !== null»
        self.declare_parameter("«param.name»", «defaultVal», descriptor=desc_«sanitizeName(param.name)»)
        self._param_«sanitizeName(param.name)» = self.get_parameter("«param.name»").value
        «ELSE»
        # Typed declaration without default value (supplied via launch file / .rossystem at runtime)
        self.declare_parameter(
            "«param.name»",
            «getRos2ParamTypeEnumPython(param.type)»,
            descriptor=desc_«sanitizeName(param.name)»
        )
        p_val_«sanitizeName(param.name)» = self.get_parameter("«param.name»")
        if p_val_«sanitizeName(param.name)».type_ != rclpy.Parameter.Type.NOT_SET:
            self._param_«sanitizeName(param.name)» = p_val_«sanitizeName(param.name)».value
        else:
            self._param_«sanitizeName(param.name)» = None
            self.get_logger().warn("Parameter '«param.name»' not provided at startup; remains None.")
        «ENDIF»
        «ENDFOR»

        self.add_on_set_parameters_callback(self._internal_on_set_parameters)

        # ----------------------------------------------------
        # 2. Publishers Initialization
        # ----------------------------------------------------
        «FOR pub : node.publisher»
        self._pub_«sanitizeName(pub.name)» = self.create_publisher(
            «pub.message.specName»,
            "«pub.name»",
            «getQosPython(pub.qos)»
        )
        «ENDFOR»

        # ----------------------------------------------------
        # 3. Subscribers Initialization
        # ----------------------------------------------------
        «FOR sub : node.subscriber»
        self._lock_«sanitizeName(sub.name)» = threading.Lock()
        self._latest_«sanitizeName(sub.name)»_msg = None
        self._has_new_«sanitizeName(sub.name)»_msg = False
        self._sub_«sanitizeName(sub.name)» = self.create_subscription(
            «sub.message.specName»,
            "«sub.name»",
            self._internal_cb_«sanitizeName(sub.name)»,
            «getQosPython(sub.qos)»
        )
        «ENDFOR»

        # ----------------------------------------------------
        # 4. Service Servers Initialization
        # ----------------------------------------------------
        «FOR srv : node.serviceserver»
        self._srv_«sanitizeName(srv.name)» = self.create_service(
            «srv.service.specName»,
            "«srv.name»",
            self.handle_«sanitizeName(srv.name)»,
            callback_group=self._cb_group
        )
        «ENDFOR»

        # ----------------------------------------------------
        # 5. Service Clients Initialization
        # ----------------------------------------------------
        «FOR client : node.serviceclient»
        self._client_«sanitizeName(client.name)» = self.create_client(
            «client.service.specName»,
            "«client.name»",
            callback_group=self._cb_group
        )
        «ENDFOR»

        # ----------------------------------------------------
        # 6. Action Servers Initialization
        # ----------------------------------------------------
        «FOR act : node.actionserver»
        self._action_server_«sanitizeName(act.name)» = ActionServer(
            self,
            «act.action.specName»,
            "«act.name»",
            execute_callback=self.execute_«sanitizeName(act.name)»,
            goal_callback=self.on_«sanitizeName(act.name)»_goal,
            cancel_callback=self.on_«sanitizeName(act.name)»_cancel,
            callback_group=self._cb_group
        )
        «ENDFOR»

        # ----------------------------------------------------
        # 7. Action Clients Initialization
        # ----------------------------------------------------
        «FOR actClient : node.actionclient»
        self._action_client_«sanitizeName(actClient.name)» = ActionClient(
            self,
            «actClient.action.specName»,
            "«actClient.name»",
            callback_group=self._cb_group
        )
        «ENDFOR»

    # ==========================================
    # SUBSCRIBER CACHED DATA ACCESSORS
    # ==========================================
    «FOR sub : node.subscriber»
    def _internal_cb_«sanitizeName(sub.name)»(self, msg: «sub.message.specName»):
        with self._lock_«sanitizeName(sub.name)»:
            self._latest_«sanitizeName(sub.name)»_msg = msg
            self._has_new_«sanitizeName(sub.name)»_msg = True
        self.on_«sanitizeName(sub.name)»_msg(msg)

    def get_latest_«sanitizeName(sub.name)»_msg(self) -> Optional[«sub.message.specName»]:
        """Get the latest cached message received on topic '«sub.name»'."""
        with self._lock_«sanitizeName(sub.name)»:
            return self._latest_«sanitizeName(sub.name)»_msg

    def has_new_«sanitizeName(sub.name)»_msg(self) -> bool:
        """Check if a new unread message has arrived on topic '«sub.name»'."""
        with self._lock_«sanitizeName(sub.name)»:
            return self._has_new_«sanitizeName(sub.name)»_msg

    def take_latest_«sanitizeName(sub.name)»_msg(self) -> Optional[«sub.message.specName»]:
        """Retrieve and clear the new message flag for topic '«sub.name»'."""
        with self._lock_«sanitizeName(sub.name)»:
            self._has_new_«sanitizeName(sub.name)»_msg = False
            return self._latest_«sanitizeName(sub.name)»_msg

    «ENDFOR»
    # ==========================================
    # INCOMING INTERFACE HOOKS (Implemented by Core Logic)
    # ==========================================

    «FOR sub : node.subscriber»
    def on_«sanitizeName(sub.name)»_msg(self, msg: «sub.message.specName») -> None:
        """Inbound subscriber callback hook for topic '«sub.name»'"""
        raise NotImplementedError("Implement on_«sanitizeName(sub.name)»_msg in your core logic subclass")

    «ENDFOR»
    «FOR srv : node.serviceserver»
    def handle_«sanitizeName(srv.name)»(self, request: «srv.service.specName».Request, response: «srv.service.specName».Response) -> «srv.service.specName».Response:
        """Inbound service handler hook for service '«srv.name»'"""
        raise NotImplementedError("Implement handle_«sanitizeName(srv.name)» in your core logic subclass")

    «ENDFOR»
    «FOR act : node.actionserver»
    def on_«sanitizeName(act.name)»_goal(self, goal_request: «act.action.specName».Goal) -> GoalResponse:
        """Goal validation hook for Action '«act.name»' (Defaults to ACCEPT)"""
        return GoalResponse.ACCEPT

    def on_«sanitizeName(act.name)»_cancel(self, goal_handle) -> CancelResponse:
        """Cancel validation hook for Action '«act.name»' (Defaults to ACCEPT)"""
        return CancelResponse.ACCEPT

    def execute_«sanitizeName(act.name)»(self, goal_handle) -> «act.action.specName».Result:
        """Execute callback for Action '«act.name»' - Domain execution logic"""
        raise NotImplementedError("Implement execute_«sanitizeName(act.name)» in your core logic subclass")

    «ENDFOR»
    def on_parameters_changed(self, parameters: List[rclpy.Parameter]) -> SetParametersResult:
        """Dynamic parameter validation hook"""
        result = SetParametersResult()
        result.successful = True
        return result

    # ==========================================
    # OUTGOING INTERFACE METHODS (Invoked by Core Logic)
    # ==========================================

    «FOR pub : node.publisher»
    def publish_«sanitizeName(pub.name)»(self, msg: «pub.message.specName») -> None:
        """Publish a message to topic '«pub.name»'"""
        if self._pub_«sanitizeName(pub.name)»:
            self._pub_«sanitizeName(pub.name)».publish(msg)

    «ENDFOR»
    «FOR client : node.serviceclient»
    def is_«sanitizeName(client.name)»_ready(self, timeout_sec: float = 1.0) -> bool:
        """Check if service '«client.name»' is available"""
        return self._client_«sanitizeName(client.name)».wait_for_service(timeout_sec=timeout_sec)

    def call_«sanitizeName(client.name)»_async(self, request: «client.service.specName».Request, callback: Optional[Callable] = None):
        """Asynchronous call to service '«client.name»' returning a Future"""
        future = self._client_«sanitizeName(client.name)».call_async(request)
        if callback:
            future.add_done_callback(callback)
        return future

    def call_«sanitizeName(client.name)»_sync(self, request: «client.service.specName».Request, timeout_sec: float = 5.0) -> Optional[«client.service.specName».Response]:
        """Thread-safe Synchronous call to service '«client.name»' with timeout"""
        if not self.is_«sanitizeName(client.name)»_ready(timeout_sec=0.5):
            self.get_logger().error("Service '«client.name»' not available for sync call.")
            return None

        event = threading.Event()
        response_holder = []

        def _done(fut):
            try:
                response_holder.append(fut.result())
            except Exception as e:
                self.get_logger().error(f"Sync service call '«client.name»' error: {e}")
            event.set()

        future = self._client_«sanitizeName(client.name)».call_async(request)
        future.add_done_callback(_done)

        if event.wait(timeout=timeout_sec) and response_holder:
            return response_holder[0]

        self.get_logger().error("Sync call to service '«client.name»' timed out.")
        return None

    «ENDFOR»
    «FOR actClient : node.actionclient»
    def send_«sanitizeName(actClient.name)»_goal_async(self, goal: «actClient.action.specName».Goal, feedback_callback: Optional[Callable] = None):
        """Asynchronously send goal to Action '«actClient.name»'"""
        if not self._action_client_«sanitizeName(actClient.name)».wait_for_server(timeout_sec=1.0):
            self.get_logger().error("Action server '«actClient.name»' not available.")
            return None
        return self._action_client_«sanitizeName(actClient.name)».send_goal_async(
            goal, feedback_callback=feedback_callback)

    def cancel_«sanitizeName(actClient.name)»_goal_async(self, goal_handle):
        """Cancel active goal for Action '«actClient.name»'"""
        if goal_handle:
            return goal_handle.cancel_goal_async()
        return None

    «ENDFOR»
    «FOR act : node.actionserver»
    def publish_«sanitizeName(act.name)»_feedback(self, goal_handle, feedback: «act.action.specName».Feedback) -> None:
        """Publish feedback for Action server '«act.name»'"""
        if goal_handle:
            goal_handle.publish_feedback(feedback)

    «ENDFOR»
    # ==========================================
    # PARAMETER ACCESSORS
    # ==========================================

    «FOR param : node.parameter»
    «val pyType = getPythonType(param.type)»
    def get_param_«sanitizeName(param.name)»(self) -> Optional[«pyType»]:
        return self._param_«sanitizeName(param.name)»

    «ENDFOR»
    def _internal_on_set_parameters(self, parameters: List[rclpy.Parameter]) -> SetParametersResult:
        res = self.on_parameters_changed(parameters)
        if not res.successful:
            return res
        for param in parameters:
            «FOR param : node.parameter»
            if param.name == "«param.name»":
                self._param_«sanitizeName(param.name)» = param.value
                self.get_logger().info(f"Parameter '«param.name»' updated to: {param.value}")
            «ENDFOR»
        success_res = SetParametersResult()
        success_res.successful = True
        return success_res
'''

    def String compileLogicStub(Package pkg, Node node) '''
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Pure Python Core Logic class for '«node.name»'.
ZERO ROS 2 runtime dependencies!
Edit this file to implement your core algorithms, data processing, and business logic.
This file is created only once and will NEVER be overwritten by the generator.
"""

from typing import Optional, Callable, Any


class «node.name»Logic:
    """
    Pure business logic for «node.name».
    """

    def __init__(self):
        «FOR pub : node.publisher»
        self._publish_«sanitizeName(pub.name)»_fn: Optional[Callable[[Any], None]] = None
        «ENDFOR»
        «FOR client : node.serviceclient»
        self._call_«sanitizeName(client.name)»_sync_fn: Optional[Callable] = None
        self._call_«sanitizeName(client.name)»_async_fn: Optional[Callable] = None
        «ENDFOR»
        «FOR actClient : node.actionclient»
        self._send_«sanitizeName(actClient.name)»_goal_fn: Optional[Callable] = None
        self._cancel_«sanitizeName(actClient.name)»_goal_fn: Optional[Callable] = None
        «ENDFOR»
        «IF node.publisher.empty && node.serviceclient.empty && node.actionclient.empty»
        pass
        «ENDIF»

    # ==========================================
    # 1. INBOUND SUBSCRIBER MESSAGE HANDLERS
    # ==========================================
    «FOR sub : node.subscriber»
    def on_«sanitizeName(sub.name)»_received(self, msg) -> None:
        """Called when a new message is received on topic '«sub.name»'."""
        pass

    «ENDFOR»
    # ==========================================
    # 2. INBOUND SERVICE REQUEST HANDLERS
    # ==========================================
    «FOR srv : node.serviceserver»
    def handle_«sanitizeName(srv.name)»(self, request, response):
        """
        Handle incoming service request for '«srv.name»'.
        Modify and return response, or populate response fields in-place.
        """
        return response

    «ENDFOR»
    # ==========================================
    # 3. INBOUND ACTION SERVER HANDLERS
    # ==========================================
    «FOR act : node.actionserver»
    def handle_goal_«sanitizeName(act.name)»(self, goal) -> bool:
        """
        Decide whether to accept or reject a goal request for action '«act.name»'.
        Return True to accept and execute, False to reject.
        """
        return True

    def handle_cancel_«sanitizeName(act.name)»(self) -> bool:
        """
        Decide whether to accept or reject a cancellation request for action '«act.name»'.
        Return True to accept cancellation, False to reject.
        """
        return True

    def execute_«sanitizeName(act.name)»(self, goal, publish_feedback: Callable[[Any], None], is_canceling: Callable[[], bool], result) -> bool:
        """
        Execute the accepted goal for action '«act.name»'.
        publish_feedback: callable to stream feedback
        is_canceling: callable returning bool if cancel was requested
        result: result object to populate
        Return True if goal succeeded, False if aborted.
        """
        return True

    «ENDFOR»
    # ==========================================
    # 4. OUTBOUND PUBLISHER METHODS
    # ==========================================
    «FOR pub : node.publisher»
    def set_«sanitizeName(pub.name)»_publisher(self, fn: Callable[[Any], None]) -> None:
        self._publish_«sanitizeName(pub.name)»_fn = fn

    def publish_«sanitizeName(pub.name)»(self, msg) -> None:
        """Publish a message to topic '«pub.name»'."""
        if self._publish_«sanitizeName(pub.name)»_fn:
            self._publish_«sanitizeName(pub.name)»_fn(msg)

    «ENDFOR»
    # ==========================================
    # 5. OUTBOUND SERVICE CLIENT CALLERS
    # ==========================================
    «FOR client : node.serviceclient»
    def set_«sanitizeName(client.name)»_client(self, sync_fn: Callable, async_fn: Callable) -> None:
        self._call_«sanitizeName(client.name)»_sync_fn = sync_fn
        self._call_«sanitizeName(client.name)»_async_fn = async_fn

    def call_«sanitizeName(client.name)»_sync(self, request, timeout_sec: float = 5.0):
        """Synchronously call service '«client.name»' with timeout."""
        if self._call_«sanitizeName(client.name)»_sync_fn:
            return self._call_«sanitizeName(client.name)»_sync_fn(request, timeout_sec)
        return None

    def call_«sanitizeName(client.name)»_async(self, request, callback: Optional[Callable] = None):
        """Asynchronously call service '«client.name»'."""
        if self._call_«sanitizeName(client.name)»_async_fn:
            return self._call_«sanitizeName(client.name)»_async_fn(request, callback)
        return None

    «ENDFOR»
    # ==========================================
    # 6. OUTBOUND ACTION CLIENT CALLERS
    # ==========================================
    «FOR actClient : node.actionclient»
    def set_«sanitizeName(actClient.name)»_client(self, goal_fn: Callable, cancel_fn: Callable) -> None:
        self._send_«sanitizeName(actClient.name)»_goal_fn = goal_fn
        self._cancel_«sanitizeName(actClient.name)»_goal_fn = cancel_fn

    def send_«sanitizeName(actClient.name)»_goal_async(self, goal, feedback_callback: Optional[Callable] = None, result_callback: Optional[Callable] = None):
        """Asynchronously send goal to action server '«actClient.name»'."""
        if self._send_«sanitizeName(actClient.name)»_goal_fn:
            return self._send_«sanitizeName(actClient.name)»_goal_fn(goal, feedback_callback, result_callback)
        return None

    def cancel_«sanitizeName(actClient.name)»_goal_async(self, goal_handle=None):
        """Cancel active goal for action client '«actClient.name»'."""
        if self._cancel_«sanitizeName(actClient.name)»_goal_fn:
            return self._cancel_«sanitizeName(actClient.name)»_goal_fn(goal_handle)
        return None

    «ENDFOR»
'''

    def String compilePythonRunner(Package pkg, Node node) '''
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import rclpy
from rclpy.executors import MultiThreadedExecutor, SingleThreadedExecutor

from «pkg.name.toLowerCase».«toSnakeCase(node.name)»_wrapper import «node.name»Wrapper
from «pkg.name.toLowerCase».«toSnakeCase(node.name)»_logic import «node.name»Logic


class «node.name»Node(«node.name»Wrapper):
    """
    Concrete ROS 2 Node coupling the pure logic with the generated wrapper.
    """

    def __init__(self):
        super().__init__()
        self.logic = «node.name»Logic()

        # Inject publisher delegates
        «FOR pub : node.publisher»
        self.logic.set_«sanitizeName(pub.name)»_publisher(self.publish_«sanitizeName(pub.name)»)
        «ENDFOR»

        # Inject service client callers
        «FOR client : node.serviceclient»
        self.logic.set_«sanitizeName(client.name)»_client(
            self.call_«sanitizeName(client.name)»_sync,
            self.call_«sanitizeName(client.name)»_async
        )
        «ENDFOR»

        # Inject action client callers
        «FOR actClient : node.actionclient»
        self.logic.set_«sanitizeName(actClient.name)»_client(
            self._wrap_send_«sanitizeName(actClient.name)»_goal_async,
            self.cancel_«sanitizeName(actClient.name)»_goal_async
        )
        «ENDFOR»

    «FOR actClient : node.actionclient»
    def _wrap_send_«sanitizeName(actClient.name)»_goal_async(self, goal, feedback_callback=None, result_callback=None):
        future = self.send_«sanitizeName(actClient.name)»_goal_async(goal, feedback_callback=feedback_callback)
        if future is None:
            return None
        if result_callback:
            def _goal_response_cb(fut):
                goal_handle = fut.result()
                if not goal_handle.accepted:
                    self.get_logger().warn("Goal rejected by action server '«actClient.name»'")
                    return
                res_fut = goal_handle.get_result_async()
                res_fut.add_done_callback(lambda rf: result_callback(rf.result().result))
            future.add_done_callback(_goal_response_cb)
        return future

    «ENDFOR»
    «FOR sub : node.subscriber»
    def on_«sanitizeName(sub.name)»_msg(self, msg) -> None:
        self.logic.on_«sanitizeName(sub.name)»_received(msg)

    «ENDFOR»
    «FOR srv : node.serviceserver»
    def handle_«sanitizeName(srv.name)»(self, request, response):
        ret = self.logic.handle_«sanitizeName(srv.name)»(request, response)
        if ret is not None and isinstance(ret, type(response)):
            return ret
        return response

    «ENDFOR»
    «FOR act : node.actionserver»
    def on_«sanitizeName(act.name)»_goal(self, goal_request):
        accept = self.logic.handle_goal_«sanitizeName(act.name)»(goal_request)
        from rclpy.action import GoalResponse
        return GoalResponse.ACCEPT if accept else GoalResponse.REJECT

    def on_«sanitizeName(act.name)»_cancel(self, goal_handle):
        accept = self.logic.handle_cancel_«sanitizeName(act.name)»()
        from rclpy.action import CancelResponse
        return CancelResponse.ACCEPT if accept else CancelResponse.REJECT

    def execute_«sanitizeName(act.name)»(self, goal_handle):
        from «act.action.specPackage».action import «act.action.specName»
        publish_fb = lambda fb: goal_handle.publish_feedback(fb)
        is_canceling = lambda: goal_handle.is_cancel_requested
        result = «act.action.specName».Result()

        success = self.logic.execute_«sanitizeName(act.name)»(
            goal_handle.request,
            publish_fb,
            is_canceling,
            result
        )

        if goal_handle.is_cancel_requested:
            goal_handle.canceled()
        elif success:
            goal_handle.succeed()
        else:
            goal_handle.abort()
        return result

    «ENDFOR»

def main(args=None):
    rclpy.init(args=args)
    node = «node.name»Node()

    «IF node.hasActionServer || node.hasServiceClients»
    # Automated Executor Selection: MultiThreadedExecutor selected
    executor = MultiThreadedExecutor()
    executor.add_node(node)
    try:
        executor.spin()
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()
    «ELSE»
    # Automated Executor Selection: SingleThreadedExecutor selected
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()
    «ENDIF»


if __name__ == '__main__':
    main()
'''

}
