name: RosTooling CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: RosTooling
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"
      - name: Debug
        run: |
          uname -a
          mvn --version
          java --version
      - name: Build and test with Maven
        run: |
          pushd RosTooling
          mvn clean verify -f plugins/de.fraunhofer.ipa.ros.parent/pom.xml
